# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gerrit/Documents/Projects/MuonSpectrumMC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gerrit/Documents/Projects/MuonSpectrumMC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gerrit/Documents/Projects/MuonSpectrumMC/CMakeFiles /home/gerrit/Documents/Projects/MuonSpectrumMC/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gerrit/Documents/Projects/MuonSpectrumMC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BSM-MuonSpectrum

# Build rule for target.
BSM-MuonSpectrum: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BSM-MuonSpectrum
.PHONY : BSM-MuonSpectrum

# fast build rule for target.
BSM-MuonSpectrum/fast:
	$(MAKE) -f CMakeFiles/BSM-MuonSpectrum.dir/build.make CMakeFiles/BSM-MuonSpectrum.dir/build
.PHONY : BSM-MuonSpectrum/fast

src/BSM-Muon.o: src/BSM-Muon.cpp.o

.PHONY : src/BSM-Muon.o

# target to build an object file
src/BSM-Muon.cpp.o:
	$(MAKE) -f CMakeFiles/BSM-MuonSpectrum.dir/build.make CMakeFiles/BSM-MuonSpectrum.dir/src/BSM-Muon.cpp.o
.PHONY : src/BSM-Muon.cpp.o

src/BSM-Muon.i: src/BSM-Muon.cpp.i

.PHONY : src/BSM-Muon.i

# target to preprocess a source file
src/BSM-Muon.cpp.i:
	$(MAKE) -f CMakeFiles/BSM-MuonSpectrum.dir/build.make CMakeFiles/BSM-MuonSpectrum.dir/src/BSM-Muon.cpp.i
.PHONY : src/BSM-Muon.cpp.i

src/BSM-Muon.s: src/BSM-Muon.cpp.s

.PHONY : src/BSM-Muon.s

# target to generate assembly for a file
src/BSM-Muon.cpp.s:
	$(MAKE) -f CMakeFiles/BSM-MuonSpectrum.dir/build.make CMakeFiles/BSM-MuonSpectrum.dir/src/BSM-Muon.cpp.s
.PHONY : src/BSM-Muon.cpp.s

src/Spectrum.o: src/Spectrum.cpp.o

.PHONY : src/Spectrum.o

# target to build an object file
src/Spectrum.cpp.o:
	$(MAKE) -f CMakeFiles/BSM-MuonSpectrum.dir/build.make CMakeFiles/BSM-MuonSpectrum.dir/src/Spectrum.cpp.o
.PHONY : src/Spectrum.cpp.o

src/Spectrum.i: src/Spectrum.cpp.i

.PHONY : src/Spectrum.i

# target to preprocess a source file
src/Spectrum.cpp.i:
	$(MAKE) -f CMakeFiles/BSM-MuonSpectrum.dir/build.make CMakeFiles/BSM-MuonSpectrum.dir/src/Spectrum.cpp.i
.PHONY : src/Spectrum.cpp.i

src/Spectrum.s: src/Spectrum.cpp.s

.PHONY : src/Spectrum.s

# target to generate assembly for a file
src/Spectrum.cpp.s:
	$(MAKE) -f CMakeFiles/BSM-MuonSpectrum.dir/build.make CMakeFiles/BSM-MuonSpectrum.dir/src/Spectrum.cpp.s
.PHONY : src/Spectrum.cpp.s

src/legendre_rule.o: src/legendre_rule.cpp.o

.PHONY : src/legendre_rule.o

# target to build an object file
src/legendre_rule.cpp.o:
	$(MAKE) -f CMakeFiles/BSM-MuonSpectrum.dir/build.make CMakeFiles/BSM-MuonSpectrum.dir/src/legendre_rule.cpp.o
.PHONY : src/legendre_rule.cpp.o

src/legendre_rule.i: src/legendre_rule.cpp.i

.PHONY : src/legendre_rule.i

# target to preprocess a source file
src/legendre_rule.cpp.i:
	$(MAKE) -f CMakeFiles/BSM-MuonSpectrum.dir/build.make CMakeFiles/BSM-MuonSpectrum.dir/src/legendre_rule.cpp.i
.PHONY : src/legendre_rule.cpp.i

src/legendre_rule.s: src/legendre_rule.cpp.s

.PHONY : src/legendre_rule.s

# target to generate assembly for a file
src/legendre_rule.cpp.s:
	$(MAKE) -f CMakeFiles/BSM-MuonSpectrum.dir/build.make CMakeFiles/BSM-MuonSpectrum.dir/src/legendre_rule.cpp.s
.PHONY : src/legendre_rule.cpp.s

src/matrix_elements.o: src/matrix_elements.cpp.o

.PHONY : src/matrix_elements.o

# target to build an object file
src/matrix_elements.cpp.o:
	$(MAKE) -f CMakeFiles/BSM-MuonSpectrum.dir/build.make CMakeFiles/BSM-MuonSpectrum.dir/src/matrix_elements.cpp.o
.PHONY : src/matrix_elements.cpp.o

src/matrix_elements.i: src/matrix_elements.cpp.i

.PHONY : src/matrix_elements.i

# target to preprocess a source file
src/matrix_elements.cpp.i:
	$(MAKE) -f CMakeFiles/BSM-MuonSpectrum.dir/build.make CMakeFiles/BSM-MuonSpectrum.dir/src/matrix_elements.cpp.i
.PHONY : src/matrix_elements.cpp.i

src/matrix_elements.s: src/matrix_elements.cpp.s

.PHONY : src/matrix_elements.s

# target to generate assembly for a file
src/matrix_elements.cpp.s:
	$(MAKE) -f CMakeFiles/BSM-MuonSpectrum.dir/build.make CMakeFiles/BSM-MuonSpectrum.dir/src/matrix_elements.cpp.s
.PHONY : src/matrix_elements.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... BSM-MuonSpectrum"
	@echo "... src/BSM-Muon.o"
	@echo "... src/BSM-Muon.i"
	@echo "... src/BSM-Muon.s"
	@echo "... src/Spectrum.o"
	@echo "... src/Spectrum.i"
	@echo "... src/Spectrum.s"
	@echo "... src/legendre_rule.o"
	@echo "... src/legendre_rule.i"
	@echo "... src/legendre_rule.s"
	@echo "... src/matrix_elements.o"
	@echo "... src/matrix_elements.i"
	@echo "... src/matrix_elements.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

